"""
convert_to_tflite.py

Converts the trained Keras model (tinyml/Model/model.h5) into a
quantized TensorFlow Lite model, then exports it as a C byte array
(model_data.h) ready to be copied into
firmware/ESP32/tinyml/model_data.h for on-device deployment.

Usage:
    python convert_to_tflite.py
"""

import os

import numpy as np
import tensorflow as tf

MODEL_DIR = os.path.join(os.path.dirname(__file__), "..", "Model")
H5_MODEL_PATH = os.path.join(MODEL_DIR, "model.h5")
TFLITE_MODEL_PATH = os.path.join(MODEL_DIR, "model.tflite")
MODEL_DATA_HEADER_PATH = os.path.join(MODEL_DIR, "model_data.h")

VAR_NAME = "g_model"
NUM_CALIBRATION_SAMPLES = 100


def representative_dataset_gen(feature_dim: int):
    """Yields random samples in the normalized input range for
    post-training int8 quantization calibration.

    For best accuracy, replace this with a generator over a held-out
    slice of the real (scaled) training data instead of random noise.
    """
    def gen():
        for _ in range(NUM_CALIBRATION_SAMPLES):
            yield [np.random.normal(0, 1, size=(1, feature_dim)).astype(np.float32)]
    return gen


def convert(quantize: bool = True):
    if not os.path.exists(H5_MODEL_PATH):
        raise FileNotFoundError(f"{H5_MODEL_PATH} not found. Run Model_Training/train.py first.")

    model = tf.keras.models.load_model(H5_MODEL_PATH)
    feature_dim = model.input_shape[-1]

    converter = tf.lite.TFLiteConverter.from_keras_model(model)

    if quantize:
        converter.optimizations = [tf.lite.Optimize.DEFAULT]
        converter.representative_dataset = representative_dataset_gen(feature_dim)
        # Full int8 quantization (uncomment for strict int8-only ops,
        # required by some TFLite Micro configurations):
        # converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
        # converter.inference_input_type = tf.int8
        # converter.inference_output_type = tf.int8

    tflite_model = converter.convert()

    with open(TFLITE_MODEL_PATH, "wb") as f:
        f.write(tflite_model)

    print(f"Saved {'quantized ' if quantize else ''}TFLite model to {TFLITE_MODEL_PATH} "
          f"({len(tflite_model)} bytes)")

    write_model_data_header(tflite_model)


def write_model_data_header(tflite_bytes: bytes):
    """Writes model_data.h C array (mirrors `xxd -i`)."""
    hex_lines = []
    for i in range(0, len(tflite_bytes), 12):
        chunk = tflite_bytes[i:i + 12]
        hex_lines.append("  " + ", ".join(f"0x{b:02x}" for b in chunk) + ",")

    header_content = f"""#ifndef MODEL_DATA_H
#define MODEL_DATA_H

// Auto-generated by tinyml/TensorFlow_Lite/convert_to_tflite.py
// Source: {os.path.basename(TFLITE_MODEL_PATH)} ({len(tflite_bytes)} bytes)
// Copy this file to firmware/ESP32/tinyml/model_data.h to deploy.

alignas(8) const unsigned char {VAR_NAME}[] = {{
{chr(10).join(hex_lines)}
}};
const unsigned int {VAR_NAME}_len = {len(tflite_bytes)};

#endif // MODEL_DATA_H
"""

    with open(MODEL_DATA_HEADER_PATH, "w") as f:
        f.write(header_content)

    print(f"Wrote C array header to {MODEL_DATA_HEADER_PATH}")


if __name__ == "__main__":
    convert(quantize=True)
